### ISSUE TITLE
The dependencies and their links are recommended to be provided

### ISSUE THREAD

**Issue by wy690251419** [mgroupntua/MSolve.IGA#5]
It seems like multiple packages are missing, including several MGroup packages and some well known packages, like Math.Net, that haven't been mentioned in the ReadMe file. The dependencies and their links are recommended to be provided.

**Comment by dimtsap** [comment]
@wy690251419  As per your request the dependencies of the projects are mentioned in the Readme file now. In addition, the NuGet.Config file is updated and you should be able to download and build the solution. Feel free to create new issues if any other problems occur.
